CREATE TABLE MATERIAL (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	CATEGORIA varchar(30) CHECK (CATEGORIA IN ('VESTUARIO', 'EQUIPAMENTOS', '')),
	PRECO NUMERIC(10, 2) NOT NULL
)

CREATE TABLE ESTOQUE (
	ID_ESTOQUE SERIAL PRIMARY KEY,
	CODIGO_MATERIAL INT NOT NULL REFERENCES MATERIAL(ID),
	QTD INT NOT NULL
)

ALTER TABLE USUARIO ADD COLUMN LOGIN VARCHAR(15) NOT NULL DEFAULT 'TESTE';
ALTER TABLE USUARIO ADD COLUMN SENHA VARCHAR(50) NOT NULL DEFAULT 'TESTE';

CREATE TABLE USUARIO (
	ID_USUARIO SERIAL PRIMARY KEY,
	NOME_USER VARCHAR(50) NOT NULL,
	PERFIL_USUARIO BOOLEAN NOT NULL,
	LOGIN VARCHAR(15) NOT NULL DEFAULT 'TESTE',
	SENHA VARCHAR(50) NOT NULL DEFAULT 'TESTE'
)

CREATE TABLE EMPRESTIMO (
	ID_EMPRESTIMO SERIAL PRIMARY KEY,
	ID_USUARIO INT REFERENCES USUARIO(ID_USUARIO) NOT NULL,
	DATA_EMPRESTIMO DATE DEFAULT CURRENT_DATE,
	DATA_DEVOLUCAO DATE,
	ID_MATERIAL INT REFERENCES MATERIAL(ID)
)

INSERT INTO MATERIAL VALUES (DEFAULT, 'BOLA', 'EQUIPAMENTOS', 120.99), 
(DEFAULT, 'COLETE', 'VESTUARIO', 55.99),
(DEFAULT, 'CHUTEIRA', 'VESTUARIO', 189.90);

INSERT INTO ESTOQUE VALUES (DEFAULT, 2, 20), 
(DEFAULT, 3, 7), (DEFAULT, 3, 4);

INSERT INTO USUARIO VALUES (DEFAULT, 'JORGE', FALSE),
(DEFAULT, 'JOÃO PEDRO', TRUE), (DEFAULT, 'CLAUDIA SANTANA', FALSE);

INSERT INTO EMPRESTIMO VALUES (DEFAULT, 1, DEFAULT, '2026-11-23', 2),
(DEFAULT, 2, DEFAULT, NULL, 3), (DEFAULT, 2, DEFAULT, NULL, 2);